# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       jolla-settings-powersave

# >> macros
BuildArch: noarch
# << macros

Summary:    Settings plugin for battery powersave management
Version:    0.1.0
Release:    1
Group:      Qt/Qt
License:    TODO
Source0:    %{name}-%{version}.tar.bz2
Requires:   coderus-qml-plugin-psmdbus-qt5 >= 2.0.1-1.9.3

%description
Battery powersave management settings plugin for the settings application


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/usr/share/jolla-settings/pages/powersave
cp -r settings/*.qml %{buildroot}/usr/share/jolla-settings/pages/powersave
mkdir -p %{buildroot}/usr/share/jolla-settings/entries
cp -r settings/*.json %{buildroot}/usr/share/jolla-settings/entries
mkdir -p %{buildroot}/usr/share/themes/jolla-ambient/meegotouch/icons
cp -r icons/*.png %{buildroot}/usr/share/themes/jolla-ambient/meegotouch/icons
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/jolla-settings/entries
%{_datadir}/jolla-settings/pages
%{_datadir}/themes/jolla-ambient/meegotouch/icons
# >> files
# << files
